### ISSUE TITLE
arrays displayed as objects

### ISSUE THREAD

**Issue by llbbl** [ccampbell/chromephp#19] opened 2012-08-24 20:41 UTC
when I var_dump the variable is an array, but I dump it to ChromePhp it says it is an object. 

anyone notice this?

**Comment by ccampbell** [comment] 2012-08-25 01:51
This is because PHP arrays can be arrays or hash tables.  If you log `ChromePhp::log(array(1, 2, 3));` I believe it will show up in the console as `[1, 2, 3]` (an array), but if you log `ChromePhp::log(array('test' => 1);` It will show up as an object because in Javascript this is an object/dictionary.

**Comment by ccampbell** [comment] 2013-04-13 04:27
Closing this out since it is not a bug.

**Closed as completed by ccampbell** 2013-04-13 04:27 UTC
